### ISSUE TITLE
Southern Cross's mining outpost has no suit cycler.

### ISSUE THREAD

**Issue by EvilJackCarver** [VulpesLegan/MITHRAStation#54]
Saw a decent location to put one while I was doing an IC tour of the facilities.

![mithrastation_2018-10-30_21-40-44](https://user-images.githubusercontent.com/1784490/47763650-926f4580-dc8f-11e8-99ac-86159f56c8e6.png)

If none of you do, I might fire up FastDMM and make that quick adjustment.

**Comment by HawkerTheGreat** [comment]
Fixed in https://github.com/VulpesLegan/MITHRAStation/pull/55
